### ISSUE TITLE
Focus out of reach

### ISSUE THREAD

**Issue by bschempp** [rennmaus-coder/Camera-Lens-AF#11]
This could be something that I am doing wrong rather than an issue.
I have an EOS 600D camera and an EF 400mm 1:2.8 L IS II USM lens. I am using LensAF 2.0.0.0 and NINA 2.1.1.3005.
The Calibrate Lens button works as expected, it slews the lens focus to max infinity, although I notice that does not seem to slew all the way to max infinity. It then leaves the focus there and sets the Position and Target Position to 100. Unfortunately, for this lens, the best focus position is now approximately -100, which cannot be reached because the focus position apparently cannot be set below zero. Perhaps the user could specify the position value after slewing to max infinity and then the Calibrate Lens button could slew to max infinity, set the position, and then move the lens to position 100.
I should note that the whole routine works very nicely if I just set the lens near optimum focus by hand and don't run the calibration routine. This, however, leaves me with an unknown shift in focus position from one night to the next. I would like to develop a focus position as a function of temperature curve and this unknown shift makes it harder, though I can see ways to get around the problem.
If this is a peculiarity of my lens I would be happy to work with you doing some testing. I could think about fixing the problem myself, but C# is not my best language.
I await comments or questions.

**Comment by rennmaus-coder** [comment]
What I could do is add an input box for the amount of focuser steps needed to reach infinity and/or an input box to define to focuser position after the calibration process. What do you think?

**Comment by bschempp** [comment]
Thanks for the reply. I downloaded the source code and have been doing some tests.
  
  
   
  
  
   First, I seem to have been mistaken about the calibration slew failing to reach the max-infinity point. I tested this by replacing the loop limit in "FocusDriver.CalibrateLens" with 5, 15, and 30. All values had exactly the same result. I have thought of several possibilities for my mistake, but I don't see any reason to change anything here. 
  
  
   
  
  
   Second, I did just as you have suggested, added a TextBox to input the value of the position after the initial slew. It appears that 320 is a good value for my camera and lens combination (when the position is initially set to 100 and then moving to 100). After setting the position I put in "FocusDriver.Move" and it all seems to work fine. This would seem to be a useful thing.
  
  
   
  
  
   A couple of suggestions that you might consider:
  
  
   1. Initializing the focuser to position 100 should be OK since I, personally, have not seen any positions below 70 during the auto-focus routine. However, 70 is disturbingly close to what appears to be effectively a hard limit at 0. I don't see any downside to increasing the initial setting.
  
  
   2. This may be just me and/or my laptop screen, but it took me some time to find the Calibrate Lens button because I couldn't see the black foreground against the very dark background of the button. Once you mouse over the button and the background changes color it is easily readable but it might still be nice if the lettering was white (like the other buttons on this screen). I tried setting the Foreground to White but that didn't work (thereby calibrating my C# skills).
  
  
   
  
  
   Thanks for your time...
  
  
   
   -BillOn 02/12/2023 11:02 PM rennmaus-coder ***@***.***> wrote:
  
  
   
    
   
   
    
   
   
   What I could do is add an input box for the amount of focuser steps needed to reach infinity and/or an input box to define to focuser position after the calibration process. What do you think?

**Comment by rennmaus-coder** [comment]
1. Sure, if you want you can create a pull request so I can merge it into the repository.
2. The button should be just like the other buttons in NINA, could be an issue with your theme, however if all other buttons are working as expected I don't really know what could be causing this.

**Comment by bschempp** [comment]
Hi-
  
  
   
  
  
   I cloned the project to a local repository, then I pulled it, then I made changes to the two files that I had worked on, then I committed it. Then I tried to push it but that failed.Camera-Lens-AF at GitHub returned error 403. Maybe you have to set some permission for me? Just so you know, I know even less about GitHub than I do about C# so it won't surprise me that I did something wrong.
  
  
   
   -Bill
  
  
   
    On 02/15/2023 6:41 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   
    Sure, if you want you can create a pull request so I can merge it into the repository.
    The button should be just like the other buttons in NINA, could be an issue with your theme, however if all other buttons are working as expected I don't really know what could be causing this.

**Comment by rennmaus-coder** [comment]
You need to create a fork first, then commit the changes to your fork and then you can create a pr, but don't worry, you can just send the changes into this issue ideally using code blocks (``` ```)

**Comment by bschempp** [comment]
Sorry, I don't understand the second part "you can just send the changes into this issue ideally using code blocks ( )".
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/15/2023 6:41 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   
    Sure, if you want you can create a pull request so I can merge it into the repository.
    The button should be just like the other buttons in NINA, could be an issue with your theme, however if all other buttons are working as expected I don't really know what could be causing this.

**Comment by rennmaus-coder** [comment]
I will grant you access to the repository tomorrow, so you can simply commit your changes to the repo.

**Comment by bschempp** [comment]
Sounds good.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/16/2023 1:07 PM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I will grant you access to the repository tomorrow, so you can simply commit your changes to the repo.

**Comment by rennmaus-coder** [comment]
I've sent you an invite, you just need to accept it and then you should be able to commit to this repository

**Comment by bschempp** [comment]
Thank you.
  
  
   
  
  
   I gather that I basically did GitHub things correctly except that I should have forked the project first so that I was working on my own copy. If I now push my changes does that directly change the project or do you still get to review them before merging? I would have no problem starting over if it will make things cleaner and safer.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/17/2023 6:17 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I've sent you an invite, you just need to accept it and then you should be able to commit to this repository

**Comment by rennmaus-coder** [comment]
I can't review them, they get pushed directly to the repository. However if there was something that would be completely wrong I could still go back to the previous commit, so feel free to push your changes 👍

**Comment by bschempp** [comment]
Thank you.
  
  
   
  
  
   I am going to wait a little while before I do the push. For one, my testing has only been to ensure that the apparent focus position of the lens is about what I expect it to be. I would really like to Calibrate the Lens and then run an Auto-focus to verify that everything works. The weather has not been too good here for the last few days. Tonight might be OK. If not then it might be another week before it is good again. Also, while it may take a few iterations to figure the best value for Focus Stop Position, once the number is determined it shouldn't change. At the moment I have to type the value in each time I calibrate the lens. I gather it that I can save and recover the value in the .profile file but I don't know how to do that yet. If you can point me to an example I'd appreciate it, if not than I will continue to work on it. It looks to me like NINA.Profile handles the overhead and that I just have to tell it that my variable should be part of the profile.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/18/2023 1:17 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I can't review them, they get pushed directly to the repository. However if there was something that would be completely wrong I could still go back to the previous commit, so feel free to push your changes 👍

**Comment by rennmaus-coder** [comment]
In the solution explorer, there is a folder called properties, open it and double click Settings. There you can add a new variable (click on the empty field and start typing). 
Examples on how to use this variable can be found in LensAF.cs

**Comment by bschempp** [comment]
Thanks!
  
  
   
  
  
   I had seen the Settings grid but didn't know what to do with it so I bypassed it. Now I know what it does.
  
  
   
  
  
   Everything is now working like I want but the weather refuses to cooperate. It is supposed to clear up in 3 or 4 days so that I can run Auto Focus after Calibrate Lens and then I can push things back.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/19/2023 12:31 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   In the solution explorer, there is a folder called properties, open it and double click Settings. There you can add a new variable (click on the empty field and start typing).Examples on how to use this variable can be found in LensAF.cs

**Comment by bschempp** [comment]
A couple of notes:
  
  
   I corrected a typo on the LensAF Installed Plugins page.
  
  
   I did nothing about the version. I figure you have a plan and will implement that.
  
  
   I did not include my lens (EF 400mm 1:2.8 L IS II USM) in the list of tested lenses. If you like, you could do so.
  
  
   
  
  
   Thanks again for the chance to work on this project.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/19/2023 5:50 PM WILLIAM SCHEMPP ***@***.***> wrote:
   
   
    
   
   
    
   
   
    Thanks!
   
   
    
   
   
    I had seen the Settings grid but didn't know what to do with it so I bypassed it. Now I know what it does.
   
   
    
   
   
    Everything is now working like I want but the weather refuses to cooperate. It is supposed to clear up in 3 or 4 days so that I can run Auto Focus after Calibrate Lens and then I can push things back.
   
   
    
    -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
    Ursula K. LeGuin
    "We have to recognize that the end game of capitalism is self-destruction."
    PZ Myers
   
   
    
     On 02/19/2023 12:31 AM rennmaus-coder ***@***.***> wrote:
    
    
     
    
    
     
    
    
    In the solution explorer, there is a folder called properties, open it and double click Settings. There you can add a new variable (click on the empty field and start typing).Examples on how to use this variable can be found in LensAF.cs

**Comment by rennmaus-coder** [comment]
Thanks for your help, I will later quickly review the changes, update the net7 version as well and then upload a new release.
Again, thank you very much and if there is nothing left to discuss you can close this issue if you want

**Comment by bschempp** [comment]
I consider it closed.
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 02/26/2023 2:26 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Thanks for your help, I will later quickly review the changes, update the net7 version as well and then upload a new release.Again, thank you very much and if there is nothing left to discuss you can close this issue if you want

**Comment by rennmaus-coder** [comment]
I implemented all the changes and created a pull request for it, so it will be available soon. Thank you for your contribution 👍

**Comment by bschempp** [comment]
Excellent. And thank you for teaching me a few things about the C# environment is VS.
   
  
  
   
   -Bill"We live in capitalism. Its power seems inescapable. So did the divine right of kings."
   Ursula K. LeGuin
   "We have to recognize that the end game of capitalism is self-destruction."
   PZ Myers
  
  
   
    On 03/04/2023 3:20 AM rennmaus-coder ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I implemented all the changes and created a pull request for it, so it will be available soon. Thank you for your contribution 👍
