### ISSUE TITLE
Start autofocus button grayed out

### ISSUE THREAD

**Issue by rgstuart** [rennmaus-coder/Camera-Lens-AF#13]
I'm attempting to use the Lens AF plugin with Canon EOS 60Da camera and a Canon 50mm EF lens. N.I.N.A. connects to the camera successfully and Manual Focus on the Imaging tab all works as described in the plugin documentation. The "Start autofocus" button on the Imaging tab is grayed out however. Am I missing something obvious here?

**Comment by rennmaus-coder** [comment]
Did you also connect your lens in the focuser tab? That is required to be able to run an Autofocus

**Comment by rgstuart** [comment]
Thank you. No I hadn't connected the lens on the focuser tab. Selecting "Genric Hub" or "POTH Hub" makes "Start autofocus" active but are either of these the correct choice? Unfortunately weather conditions mean I can't try a live test for a few days.

**Comment by rennmaus-coder** [comment]
No, there should appear your lens name after you connected your camera (if you are using a third party lens, it may be some random characters).
So first connect your camera, then go to the focuser tab and hit rescan if it isn't already in the list and then select your lens and connect to it

**Comment by rgstuart** [comment]
Doing a scan revealed the lens and selecting it made "Start autofocus" active. Given the difficulties of attaining good focus with camera lenses I see Lens AF as being a tremendous benefit. Looking forward to giving it a tryout. You might consider extending the plugin documentation so you wouldn't have to waste your time answering silly questions like this. Thanks for your help. Much appreciated.
