### ISSUE TITLE
Camera Lens AF After Time Amount Input shows "min" but the seems to be used as seconds

### ISSUE THREAD

**Issue by Kyntharha** [rennmaus-coder/Camera-Lens-AF#4]
![image](https://user-images.githubusercontent.com/32623622/150520456-c917d860-937e-4e2a-8bc8-2060aa4e0ee5.png)

**Comment by Kyntharha** [comment]
Not part of this issue but: it Lens AF worked fine with my Canon Eos 700D
Thanks for the work you put into this:)

**Comment by rennmaus-coder** [comment]
Hi, thank you for the issue! I just published a new version with a fix for this along with some other cool features.
