### ISSUE TITLE
Ideas: 2nd Exposure // more than 9 intervals // logging

### ISSUE THREAD

**Issue by TheSkyseeker** [rennmaus-coder/Camera-Lens-AF#6]
Hi (oder Servus) Rennmaus,

I don't have an EOS Camera yet, but plan to get one for widefield captures, so your plugin comes in handy :-)

As an enthusiastic owner of an Astromechanics adapter, I would like to provide some input here. 

In the meantime I always take two shots per focus point, the HFR curve becomes more stable, costs some time but pays off.

That you come up with 9 intervals, I'm sure you do for a good reason. With more intervals you could adjust even more finely, and on the other hand see by logging when it is no longer worthwhile. For example, I can't get my Canon 50mm with my Astromechanics from infinity to the best focus point (HFR worst equals four times the value of HFR best) within only 9 shots.

**Comment by rennmaus-coder** [comment]
(Ich schreibe jetzt hier einfach auf deutsch)
Servus und danke für dein Feedback. Wenn die Standard schrittgröße nicht ausreicht, kannst du sie in den Plugin Optionen verändern. So sollte sich eigentlich jedes Objektiv fokussieren lassen. Leider kann die benötigte schrittgröße von Objektiv zu Objektiv stark variieren, zb bei meinem 100-400 braucht sich step size 6, bei meinem 70-200 jedoch nur 2...

**Comment by TheSkyseeker** [comment]
Servus,
ich meinte damit nicht die Schrittgröße (die ist absolut ausreichend konfigurierbar), sondern die Option, mit mehr als 9 Invervallen (und damit natürlich auch eine kleinere Schrittgröße) noch bessere Ergebnisse zu erreichen.

Lass mich dies folgendermaßen verdeutlichen:
Ich weiß, dass die Schrittgröße und Co nicht 1:1 mit dem Astromechanics vergleichbar ist, aber die Relationen sind ähnlich beim jeweils gleichen Objektiv.

Wenn ich bis unendlich fokussiere, muss ich 400 Schritte zurückgehen, dort ist dann bei +/-20 Schritten der ideale Fokuspunkt. Dort wird dann (in 10 Intervallen) mit einer Schrittgröße von 4 nach eben jenem Punkt gesucht, die HFR unterscheidet sich dort merklich, also kein sinnloser Vergleich zwischen HFR 2.4 mit 2.5 ... 
Soll also heißen, dass ich mit einer Schrittgröße von 4 erst einmal quasi 100 "Intervalle" (4*100=400) zurückgehen müsste, dann ich überhaupt in der richtigen Range bin... 
Deshalb frage ich mich, wie man mit "nur" 9 Intervallen beim Lens AF "an's Ziel kommt".

Beste Grüße und CS
Steven

**Comment by rennmaus-coder** [comment]
Ich kann die Anzahl der Intervalle variabel machen, das ist eine gute Idee. Ist es das was du meinst?

**Comment by TheSkyseeker** [comment]
Ja, genau das meinte ich.

Kannst du herausbekommen, wie viele Small Steps einem Big Step entsprechen?

Damit kann man schnell herunterrechnen, wie viele Intervalle man braucht, um bei ein 100-400er mit einer Step Size von 1 statt 6 zu arbeiten. Ob jetzt wirklich ne 1 notwendig ist, sei dahingestellt..

Je kleiner die Size desto genauer ist man, braucht aber auch mehr Zeit. Hätte dafür auch eine Idee..

**Comment by rennmaus-coder** [comment]
Das kann ich in die nächste Version reinpacken. Ich schaue mal wie viele small steps einem big step entsprechen, kann aber sein, dass das vom Objektiv abhängt

**Comment by TheSkyseeker** [comment]
Man könnte auch einen "Initial Offset to to get into the focus range" einfügen.
So kann man gleich am Anfang wenn auf unendlich fokussiert mehrfach Step Size x zurückfahren, und ab da mit einer kleinen Step Size das Prozedere durchlaufen.

**Comment by rennmaus-coder** [comment]
Wenn die neue Version veröffentlicht wird, hat sie die features Initial Offset und Iterations. Wenn das alles ist, würde ich den issue schließen

**Comment by TheSkyseeker** [comment]
Willst du noch die Option von zwei Exposures pro Step einbinden, und dann jeweils den besseren HFR verwenden? So haben Verwackler etc. weniger Auswirkung

**Comment by rennmaus-coder** [comment]
Sorry, das habe ich komplett aus den Augen verloren. Habe aber auch schon seit langem nicht mehr an dem Projekt gearbeitet.... Eher nicht, das sollte die meiste Zeit mit einem Bild funktionieren, so gesehen wäre das relativ viel "verschwendete" Zeit, da der Autofokus dann ja doppelt so lange dauern würde. Sorry nochmal und danke für deine Vorschläge. Wenn sonst nichts anliegt würde ich den issue dann schließen. Clear Skies!

**Comment by TheSkyseeker** [comment]
Kein Thema, ich kam nur auf die Idee, da einige im NINA eigenen Autofocus so vorgehen um den perfekten Punkt zu finden. 

Wichtiger ist aber m.E. tatsächlich die Menge an Intervallen. 

CS Steven 

Am 07.09.2022 um 15:13 schrieb rennmaus-coder ***@***.***>:

﻿
Sorry, das habe ich komplett aus den Augen verloren. Habe aber auch schon seit langem nicht mehr an dem Projekt gearbeitet.... Eher nicht, das sollte die meiste Zeit mit einem Bild funktionieren, so gesehen wäre das relativ viel "verschwendete" Zeit, da der Autofokus dann ja doppelt so lange dauern würde. Sorry nochmal und danke für deine Vorschläge. Wenn sonst nichts anliegt würde ich den issue dann schließen. Clear Skies!
